export const ActionTypes ={
    AUTH_LOGIN : 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    REDIRECT: 'REDIRECT',
    SEAT_TYPE: 'SEAT_TYPE',
    APPLY_FARE: 'APPLY_FARE',
    APPLY_FARE_ALL: 'APPLY_FARE_ALL',
    CREATE_ROUTE: 'CREATE_ROUTE',
    CREATE_STOPPINGS: 'CREATE_STOPPINGS',
    ADD_SEATS: 'ADD_SEATS',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    SET_ERROR: 'SET_ERROR',
    GET_ITEMS: 'GET_ITEMS',
    CREATE_BOARDING: 'CREATE_BOARDING',
    CREATE_DROPPING: 'CREATE_DROPPING',
    EDIT_BOARDING: 'EDIT_BOARDING',
    EDIT_DROPPING: 'EDIT_DROPPING',
    GET_USERS: 'GET_USERS'  

}